version: 2
updates:
  # Dependências JavaScript/Bun
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'monday'
    open-pull-requests-limit: 5
    commit-message:
      prefix: 'chore(deps)'
    groups:
      svelte:
        patterns:
          - '@sveltejs/*'
          - 'svelte*'
          - 'vite*'
      smui:
        patterns:
          - '@smui/*'
      i18n:
        patterns:
          - '@inlang/*'
          - 'paraglide*'

  # GitHub Actions
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'monthly'
    open-pull-requests-limit: 3
    commit-message:
      prefix: 'ci(deps)'
