name-template: 'v$RESOLVED_VERSION 🎓'
tag-template: 'v$RESOLVED_VERSION'
template: |
  ## 🎯 Destaques desta versão

  $CHANGES

  ## 🙏 Agradecimentos

  Obrigado a todos que contribuíram para esta versão!

  **Instalação**: Acesse https://araujosemacento.github.io/ED-Acima_das_Nuvens/

  ---

  **Lançamento completo**: https://github.com/araujosemacento/ED-Acima_das_Nuvens/compare/$PREVIOUS_TAG...v$RESOLVED_VERSION

categories:
  - title: '🎮 Jogo Narrativo'
    labels:
      - '🎮 game'
  - title: '📚 Conteúdo Educacional'
    labels:
      - '📚 educational'
      - '🐍 python'
  - title: '✨ Novas Funcionalidades'
    labels:
      - '✨ enhancement'
  - title: '🎨 Melhorias de UI/UX'
    labels:
      - '🎨 ui/ux'
      - '♿ accessibility'
  - title: '🐛 Correções de Bugs'
    labels:
      - '🐛 bug'
  - title: '⚡ Performance'
    labels:
      - '⚡ performance'
  - title: '🌍 Internacionalização'
    labels:
      - '🌍 i18n'
  - title: '🔒 Segurança'
    labels:
      - '🔒 security'
  - title: '🚀 DevOps e CI/CD'
    labels:
      - '🚀 ci/cd'
      - '🏗️ build'
  - title: '📦 Dependências'
    labels:
      - '📦 dependencies'
  - title: '📝 Documentação'
    labels:
      - '📝 docs'
  - title: '🔧 Manutenção'
    labels:
      - '🔧 chore'
      - '⚙️ config'
  - title: '🧪 Testes'
    labels:
      - '🧪 test'
  - title: '💥 Breaking Changes'
    labels:
      - '💥 breaking change'

version-resolver:
  major:
    labels:
      - '💥 breaking change'
  minor:
    labels:
      - '✨ enhancement'
      - '📚 educational'
      - '🎮 game'
      - '🎨 ui/ux'
      - '⚡ performance'
      - '🌍 i18n'
      - '♿ accessibility'
  patch:
    labels:
      - '🐛 bug'
      - '🔒 security'
      - '📝 docs'
      - '🔧 chore'
      - '🧪 test'
      - '📦 dependencies'
      - '🚀 ci/cd'
      - '🏗️ build'
      - '⚙️ config'
  default: patch

autolabeler:
  - label: '📚 educational'
    files:
      - 'static/scripts/*.py'
      - 'src/lib/components/PyodideInteractive.svelte'
      - 'src/lib/stores/pyodide.js'
  - label: '🎮 game'
    files:
      - 'src/lib/components/Welcome.svelte'
      - 'src/routes/game/**/*'
  - label: '🎨 ui/ux'
    files:
      - 'src/lib/components/*.svelte'
      - 'src/theme/**/*'
      - 'src/app.scss'
      - 'static/smui*.css'
  - label: '🌍 i18n'
    files:
      - 'messages/*.json'
      - 'src/lib/paraglide/**/*'
  - label: '🚀 ci/cd'
    files:
      - '.github/workflows/*.yml'
      - '.github/workflows/*.yaml'
  - label: '📦 dependencies'
    files:
      - 'package.json'
      - 'bun.lock'
  - label: '⚙️ config'
    files:
      - '*.config.js'
      - '*.config.json'
      - '.github/**/*'
  - label: '📝 docs'
    files:
      - '*.md'
      - 'docs/**/*'
  - label: '🧪 test'
    files:
      - 'tests/**/*'
      - '**/*.test.js'
      - '**/*.spec.js'

exclude-labels:
  - 'skip-changelog'
  - '🔄 duplicate'
  - '❌ wontfix'
  - '❓ question'
