name: 'ED | Acima das Nuvens'
description: 'Plataforma interativa que combina jogo narrativo RPG com execução Python no browser'
topics:
  - 'interactive'
  - 'python'
  - 'svelte'
  - 'sveltekit'
  - 'pyodide'
  - 'material-design'
  - 'browser-python'
  - 'data-structures'
  - 'algorithms'
  - 'rpg-game'
  - 'typescript'
  - 'javascript'
  - 'web-development'
  - 'github-pages'
  - 'internationalization'
  - 'accessibility'
  - 'responsive-design'
  - 'progressive-web-app'

homepage: 'https://araujosemacento.github.io/ED-Acima_das_Nuvens/'
documentation: 'https://github.com/araujosemacento/ED-Acima_das_Nuvens/blob/main/README.md'

# Repository settings
has_issues: true
has_projects: false
has_wiki: true
has_downloads: false

# Enable discussions
has_discussions: true

# Default branch
default_branch: 'main'

# Enable automatic security fixes
enable_automated_security_fixes: true
enable_vulnerability_alerts: true

# Branch protection (when possible)
branch_protection:
  main:
    required_status_checks:
      strict: true
      contexts:
        - 'lint'
        - 'test'
        - 'build-test'
    enforce_admins: false
    required_pull_request_reviews:
      required_approving_review_count: 1
      dismiss_stale_reviews: true
      require_code_owner_reviews: true
    restrictions: null
    allow_force_pushes: false
    allow_deletions: false
